version: "3"
services:
  app:
    image: ng-local-docker
    volumes:  
      - ./:/usr/src/app
    working_dir: /usr/src/app
    environment:
      NODE_ENV: development
    ports:
      - 4200:4200
    # command: npm run start
    command: >
      sh -c "cp -r ../temp/node_modules node_modules &&
        npm run start"
    